### PR TITLE
qtgui/QFosphorColorMapper: std::sstream+string instead of sscanf("%m")+char*

### LINKED ISSUE #6648: [MSVC] 'sscanf()' and "%m"
### Feature Description

Building **gnuradio-qtgui.dll** on MSVC (with OpenGL support), I noted this important warning:
```c
QFosphorColorMapper.cc(67): warning C4476: 'sscanf' : unknown type field character 'm' in format specifier
QFosphorColorMapper.cc(67): warning C4474: 'sscanf' : too many arguments passed for format string
QFosphorColorMapper.cc(67): note: placeholders and their parameters expect 1 variadic arguments, but 2 were provided
```

A support for `%m` seems Linux specific too me. Ref:  http://linux.die.net/man/3/scanf 

No word on this on [MSDN](https://learn.microsoft.com/en-us/cpp/c-runtime-library/scanf-type-field-characters?view=msvc-170). Not sure if MinGW-w64 supports this. 

For MSVC, that code will crash at runtime; `free()` of an illegal pointer.

I tried this feeble attempt instead:
```diff
--- a/gr-qtgui/lib/QFosphorColorMapper.cc 2023-04-26 15:19:11
+++ b/gr-qtgui/lib/QFosphorColorMapper.cc 2023-05-04 13:47:35
@@ -64,7 +64,13 @@

         /* Are we in a palette ? */
         if (kp < 0) {
+#ifdef _WIN32
+            char buf[41] = { '\0' };
+            name = buf;
+            sscanf(line.constData(), "%d %40s", &kp, buf);
+#else
             sscanf(line.constData(), "%d %ms", &kp, &name);
+#endif

             if (kp)
                 gradient = new QLinearGradient();
@@ -75,8 +81,10 @@

             addPalette(name, pixmap);

+#ifdef _WIN32
             /* Release name & prepare for next */
             free(name);
+#endif
             name = NULL;

             kp = -1;
@@ -96,7 +104,9 @@
                 delete gradient;
                 gradient = NULL;

+#ifdef _WIN32
                 free(name);
+#endif
                 name = NULL;

                 kp = -1;
```

Must be a better way.

### Feature Urgency

high (impacts broad portion of ecosystem)

### More Information

_No response_

### PR DESCRIPTION
**Pull request by marcusmueller**
Fixes #6648

(hopefully)

## Description

#6648 highlights that we introduced GCC extension of the C sscanf to the codebase. That `%ms` is handy when dealing with unknown length string data in C: it avoids having to scan for string length first, then `malloc` a buffer, then do the actual `scanf`. But: That problem is a C-exclusive problem. C++ has `std::string`, and `std::stringstream` (though the latter *could* be nicer).

So, we replace the usage of sscanf and raw C strings with `std::string` altogether and hopefully arrive at easier to read code, as well.

## Related Issue

- #6648, which this is supposed to fix
- #6515, which introduced the code

## Which blocks/areas does this affect?

- qtgui-internal (specifically, Fosphor-internal)

## Testing Done

none, due to hot laptop on hot train

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by willcode — APPROVED** [review]
Code looks good. We need someone report that this works before merging.

**Comment by marcusmueller** [comment]
I think @gmeyerho is the person I'd trust on that – he understands what the code actually does much better than I do! I just really did a "mechanical" modification, he's our expert :)

**Comment by gmeyerho** [comment]
I tested this out, but I am not seeing the color heat map anymore, just the red and white lines for max and average hold. If I remove this commit, I can see the heat map again. I didn't have time to look into this more than building and testing to see why that is. I will try to find time to figure out which part is causing that tomorrow.

**Comment by marcusmueller** [comment]
:sweat: didn't mean to break things! Thanks for having a look!

File: gr-qtgui/lib/QFosphorColorMapper.cc [hunk 1]
```diff
@@ -64,10 +67,13 @@ int QFosphorColorMapper::loadFromFile(QFile& file)
 
         /* Are we in a palette ? */
         if (kp < 0) {
-            sscanf(line.constData(), "%d %ms", &kp, &name);
+            ss.str() = line.toStdString();
```
Comment (gmeyerho) [inline gr-qtgui/lib/QFosphorColorMapper.cc:70]: I found this needs to be ss.str(line.toStdString()); instead, it looks like ss.str() just returns a copy of the current contents rather than a reference that can be used to set the contents of the stringstream.

File: gr-qtgui/lib/QFosphorColorMapper.cc [hunk 2]
```diff
@@ -64,10 +67,13 @@ int QFosphorColorMapper::loadFromFile(QFile& file)
...
+            ss >> kp;
+            ss >> name;
```
Comment (gmeyerho) [inline gr-qtgui/lib/QFosphorColorMapper.cc:72]: Something about either of these, probably the name one since it's last, is causing an error. I didn't dig into exactly the error case, but making the other change and inserting a ss.clear(); after this line causes the color heat-map to appear like before

Comment (marcusmueller) [reply gr-qtgui/lib/QFosphorColorMapper.cc:72]: Then let's do that!

File: gr-qtgui/lib/QFosphorColorMapper.cc [hunk 3]
```diff
@@ -76,29 +83,24 @@ int QFosphorColorMapper::loadFromFile(QFile& file)
...
+            name.clear();
 
             kp = -1;
         } else {
-            float f[4];
+            std::array<float, 4> f;
 
             /* Read data point */
-            sscanf(line.constData(), "%f %f %f %f", f, f + 1, f + 2, f + 3);
+            ss.str() = line.toStdString();
```
Comment (gmeyerho) [inline gr-qtgui/lib/QFosphorColorMapper.cc:93]: There was one more case of this needing to be ss.str(line.toStdString()); down here, sorry didn't call it out in the above comment. Though the color seems to work without this change, but should probably still make it

**Review by gmeyerho — APPROVED** [review]

File: gr-qtgui/lib/QFosphorColorMapper.cc (hunk 3 above)
Comment (marcusmueller) [reply gr-qtgui/lib/QFosphorColorMapper.cc:93]: I should have fixed that by myself, you shouldn't have to call out individual instances of systematic problems … sorry.
