### PR TITLE
blocks: Reopen wavfile_sink after stop().

### LINKED ISSUE #7456: `wavfile_sink` does not continue after lock/unlock
### What happened?

It's bug or feature? WAV file sinking stopped after lock()/unlock(). So any flowgraph reconfigure are not posible

### System Information

OS: Debian 12
GR Installation Method: Conda (conda-forge)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

```python
import pathlib
import time

import gnuradio as gr
import gnuradio.analog
import gnuradio.blocks
import gnuradio.gr


def foo(var, sr, fp):
    print(f'test {var!r}')
    tb = gr.gr.top_block('Test')
    src = gr.analog.noise_source_f(gr.analog.GR_GAUSSIAN, 1, 0)
    thr = gr.blocks.throttle(gr.gr.sizeof_float, sr)

    if var == 'file':
        sink = gr.blocks.file_sink(gr.gr.sizeof_float, str(fp))
    else:
        sink = gr.blocks.wavfile_sink(
            str(fp),
            1,
            sr,
            gr.blocks.FORMAT_WAV,
            gr.blocks.FORMAT_FLOAT,
            False
        )

    tb.connect(src, thr, sink)

    tb.start()

    time.sleep(3)
    tb.lock()
    st = fp.stat()
    print(f'mt={st.st_mtime:.3f} sz={st.st_size}')
    tb.unlock()

    time.sleep(3)
    tb.stop()
    tb.wait()
    st = fp.stat()
    print(f'mt={st.st_mtime:.3f} sz={st.st_size}')


if __name__ == '__main__':
    print('GNURadio', gr.gr.version())
    sr = 48000
    fp = pathlib.Path('/tmp/sink_test')
    for var in ('file', 'wav'):
        foo(var, sr, fp)

```

### Relevant log output

```shell
GNURadio 3.10.10.0
test 'file'
mt=1722331004.135 sz=557024
mt=1722331007.207 sz=1114048
test 'wav'
mt=1722331010.287 sz=557104
mt=1722331010.387 sz=557104
```

### PR DESCRIPTION
**Pull request by sladecek**
## Description

The flowgraph uses the stop() method of a block 
to indicate that it has been locked for
configuration. I believe the correct behavior for
file-based sinks is to write all data and headers
to disk, flush the file buffers, but avoid closing the file 
(see also #2590).

This behavior is implemented in the
file_sink. Since the file_sink is very simple and
does not require updating headers, flushing the
file is sufficient.

On the other hand, wavfile_sink can write to
several file formats, some of which include
headers. The implementation relies on libsndfile,
which provides a flush function. However, the
source code indicates that this function does not
update headers before flushing.

The current implementation of wavfile_sink calls
the close() method within the stop() method to
ensure the file on disk is correct. However, this
also closes the file.

My solution is to add a flag for automatic
reopening. When the file is opened, its filename
is stored. When the stop() method is called, the
file is closed, and the automatic reopen flag is
set. Later, within the start() method the file is
automatically reopened in append mode.

## Related Issue
Fixes #7456 .

## Which blocks/areas does this affect?
blocks/wavfile_sink

## Testing Done
- make test
- the reproduction steps from #7456

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

File: gr-blocks/lib/wavfile_sink_impl.cc [hunk 1]
```diff
@@ -255,6 +265,20 @@ bool wavfile_sink_impl::stop()
...
+}
+
+bool wavfile_sink_impl::start()
+{
+    gr::thread::scoped_lock guard(d_mutex);
+    if (d_should_reopen) {
+        d_should_reopen = false;
+        if (!open_file_for_append()) {
+            d_logger->error("Failed to reopen output file after reconfiguration.");
+        }
```
Comment (marcusmueller) [inline gr-blocks/lib/wavfile_sink_impl.cc:280]: Can the sink continue to work in this situation?
If not, we should `return false` here!

**Review by marcusmueller — COMMENTED** [review]
Needs one clarification; other than that, looks

File: gr-blocks/lib/wavfile_sink_impl.cc (hunk 1 above)
Comment (sladecek) [reply gr-blocks/lib/wavfile_sink_impl.cc:281]: I agree, in this situation is more correct to return `false`.

**Review by marcusmueller — APPROVED** [review]
