### PR TITLE
runtime: Process system messages before others

### LINKED ISSUE #4348: qa_packet_headerparser_b: Flaky
I thought this would have been fixed by 02b909bbcfc27ffea582b06dd2f95e478e0cdee2, but that just changed the error:

```
214/244 Test #214: qa_packet_headerparser_b .....................***Failed    5.87 sec
..F.
======================================================================
FAIL: test_003_ofdm (__main__.qa_packet_headerparser_b)
Header 1: 193 bytes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/gnuradio/gnuradio/gr-digital/python/digital/qa_packet_headerparser_b.py", line 121, in test_003_ofdm
    self.waitFor(lambda: sink.num_messages() == 2)
  File "/__w/gnuradio/gnuradio/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 147, in waitFor
    self.fail(fail_msg)
AssertionError: Timeout exceeded during call to waitFor()!

----------------------------------------------------------------------
Ran 4 tests in 5.621s
```

Latest failure: https://github.com/gnuradio/gnuradio/pull/4340/checks?check_run_id=2081291093

### PR DESCRIPTION
**Pull request by argilo**
## Description
Various tests involving message passing fail intermittently, for example `qa_packet_headerparser_b`. One or more messages fail to arrive at the `message_debug` block when the flow graph stops processing samples. This occurs due to a race condition in `tpb_thread_body`.

The [main loop of `tpb_thread_body`](https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gnuradio-runtime/lib/tpb_thread_body.cc#L70-L152) iterates over the message queues in an undefined order, reading pending messages from each. One of these queues is the special "system" queue; if a "done" message arrives on this queue, then the corresponding handler sets `d_finished` to true, which will later cause the main loop to exit:

https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gnuradio-runtime/lib/block.cc#L759-L770

The following race condition can occur:

1. The main loop reads from the "foo" message queue, and finds it empty.
2. A message arrives on the "foo" queue.
3. A "done" message arrives on the "system" queue.
4. The main loop reads from the "system" queue, finds the "done" message, and sets `d_finished` to true.
5. The main loop exits, because `d_finished` is true.

The message on the "foo" queue is never processed.

To solve this problem, I've used a custom comparator to order the message queues such that the "system" queue comes first. This guarantees that after a "done" message is processed, all other queues will be processed at least once before the main loop exits.

## Related Issue
Fixes #4348.

## Which blocks/areas does this affect?
Message passing in the thread-per-block scheduler.

## Testing Done
I ran `qa_packet_headerparser_b` in a loop (`while gr-digital/python/digital/qa_packet_headerparser_b_test.sh; do :; done`) to verify that it no longer fails intermittently.

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] ~~I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.~~
- [x] ~~I have added tests to cover my changes~~, and all previous tests pass.

### CODE REVIEW

**Comment by argilo** [comment]
Something is broken, because `set_msg_handler` is now raising this exception when I start up Gqrx:

https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gnuradio-runtime/include/gnuradio/basic_block.h#L386-L394

**Comment by argilo** [comment]
It appears the exception is thrown when trying to register a `system` handler for the `fix_cc` block in gr-iqbal. The problem only occurs some of the time.

**Comment by argilo** [comment]
Never mind. The issue was simply that I needed to rebuild gr-iqbal to pick up the change to `basic_block.h`.

**Review by willcode — APPROVED** [review]
Since the order is currently undefine, this shouldn't hurt anything. It makes sense to process system messages first, giving them a higher priority than other messages.

File: gnuradio-runtime/include/gnuradio/basic_block.h [hunk 1]
```diff
@@ -28,6 +28,21 @@
...
+public:
+    bool operator()(pmt::pmt_t const& p1, pmt::pmt_t const& p2) const
+    {
+        std::string s1 = pmt::symbol_to_string(p1);
+        std::string s2 = pmt::symbol_to_string(p2);
+        if (s1 == "system")
+            s1 = "";
+        if (s2 == "system")
+            s2 = "";
+        return s1 < s2;
```
Comment (jdemel) [inline gnuradio-runtime/include/gnuradio/basic_block.h:42]: First off, message queues should always be identified via pmts. cf. https://github.com/gnuradio/gnuradio/blob/fa8953de2ae67990ccb052af08affac073e106ae/gnuradio-runtime/lib/basic_block.cc#L76
and the following methods. Also, `is_symbol()` requires that the PMT is a string.
https://github.com/gnuradio/gnuradio/blob/fa8953de2ae67990ccb052af08affac073e106ae/gnuradio-runtime/lib/pmt/pmt_int.h#L44

I suggest to add a private member to `msg_queue_comparator`
```c++
const pmt::pmt_t d_system_queue_key = pmt::mp("system");
```
Then you can compare the inputs `p1` and `p2` via `pmt::equal`. It looks like this is how its done in the `pmt` implementation. It might avoid some corner cases. In case it is not the system queue, I suggest to fall back to `pmt::comparator`.

File: gnuradio-runtime/include/gnuradio/basic_block.h [hunk 2]
```diff
@@ -28,6 +28,21 @@
 
 namespace gr {
 
+class msg_queue_comparator
+{
+public:
+    bool operator()(pmt::pmt_t const& p1, pmt::pmt_t const& p2) const
```
Comment (jdemel) [inline gnuradio-runtime/include/gnuradio/basic_block.h:34]: I suggest to give the parameters more descriptive names. e.g. `queue_key0`.

**Review by jdemel — CHANGES_REQUESTED** [review]
Thanks for this PR. I have a few suggestions.

File: gnuradio-runtime/include/gnuradio/basic_block.h [hunk 3]
```diff
@@ -28,6 +28,28 @@
...
+private:
+    const pmt::pmt_t d_system_port = pmt::intern("system");
+
+public:
+    bool operator()(pmt::pmt_t const& queue_key1, pmt::pmt_t const& queue_key2) const
+    {
+        bool is_system1 = pmt::eqv(queue_key1, d_system_port);
+        bool is_system2 = pmt::eqv(queue_key2, d_system_port);
+
+        if (is_system1 && is_system2)
```
Comment (willcode) [inline gnuradio-runtime/include/gnuradio/basic_block.h:42]: This is equivalent to
```
if (is_system2) return false;
else if (is_system1) return true;
else ...
```
but perhaps it's more obvious the way you have it.

Comment (argilo) [reply gnuradio-runtime/include/gnuradio/basic_block.h:42]: I left it the long way since it seemed a bit more understandable. I'll leave it unless there's a strong preference to shorten it.

Comment (willcode) [reply gnuradio-runtime/include/gnuradio/basic_block.h:42]: Nah, the compiler will take care of it anyway.

Comment (jdemel) [reply gnuradio-runtime/include/gnuradio/basic_block.h:42]: I suggest to do a quick check with https://godbolt.org/
You never know what your compiler does.

File: gnuradio-runtime/include/gnuradio/basic_block.h [hunk 4]
```diff
@@ -28,6 +28,28 @@
...
+            return false;
+        else if (is_system1 && !is_system2)
+            return true;
+        else if (!is_system1 && is_system2)
+            return false;
+        else
+            return queue_key1 < queue_key2;
```
Comment (jdemel) [inline gnuradio-runtime/include/gnuradio/basic_block.h:49]: How is this comparison defined? Would it be an option to use `pmt::comparator`?

**Review by jdemel — COMMENTED** [review]
Thanks for the updates. I have two more comments. Besides LGTM.

File: gnuradio-runtime/include/gnuradio/basic_block.h (hunk 3 above)
Comment (argilo) [reply gnuradio-runtime/include/gnuradio/basic_block.h:42]: The code is actually quite a bit simpler the other way, since the `is_system1` and `is_system2` don't need to be separately defined. I'll rewrite it.

File: gnuradio-runtime/include/gnuradio/basic_block.h (hunk 4 above)
Comment (argilo) [reply gnuradio-runtime/include/gnuradio/basic_block.h:49]: I incorrectly assumed it would use the comparator. I'll change the code to explicitly call it.

**Comment by argilo** [comment]
The code is now refactored, and I verified that `qa_packet_headerparser_b_test` still passes reliably.
