### PR TITLE
Fix the potential for Static Initialization Order Fiasco

### LINKED ISSUE #1711: Move const initializations of PMTs into headers
as #1697 showed, having these in the .cc files can seemingly, under conditions I don't fully grok, lead to hazard. Anyway, having them static const in the header is probably what one wants, anyway. So let's do that.

### PR DESCRIPTION
**Pull request by marcusmueller**
Found thanks to #1697.

Closes #1711.

### CODE REVIEW

**Comment by marcusmueller** [comment]
I'll remove this comment once complete: please don't review before.

File: gr-uhd/include/gnuradio/uhd/usrp_block.h [hunk 1]
```diff
@@ -30,6 +30,24 @@
 namespace gr {
   namespace uhd {
 
+    const pmt::pmt_t cmd_chan_key();
```
Comment (noc0lour) [inline gr-uhd/include/gnuradio/uhd/usrp_block.h]: Exposing those keys with `GR_UHD_API` fixes the missing symbols in the lib.
