### PR TITLE
filter: make gen_interpolator_taps run on modern gfortran

### LINKED ISSUE #6521: praxis.f has compiler errors and thus generating interpolator taps is impossible
### What happened?

```
gfortran -c -o praxis.o praxis.f
```

### System Information

OS: Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
GR: 3.10.0.0 from Github

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.0.0

### Steps to Reproduce the Problem

```
cd gr-filter/lib/gen_interpolator_taps

gfortran -c -o praxis.o praxis.f
```
alternatively
```
f77 -c -o praxis.o praxis.f
```

### Relevant log output

```shell
praxis.f:23:72:

   23 |  10      X(I) = INITV(I)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 10 at (1)
praxis.f:37:72:

   37 |  30      OUT(I) = X(I)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 30 at (1)
praxis.f:991:24:

  991 |          CALL FLIN(X2,J,F,F2)
      |                        1
Error: Interface mismatch in dummy procedure ‘f’ at (1): Type mismatch in function result (REAL(8)/REAL(4))
praxis.f:1038:21:

 1038 |    40 CALL FLIN(X2,J,F,F2)
      |                     1
Error: Interface mismatch in dummy procedure ‘f’ at (1): Type mismatch in function result (REAL(8)/REAL(4))
```
```

### PR DESCRIPTION
**Pull request by marcusmueller**
also, fix C to actually be standards-compliant

also, a .gitignore for compilation results

## Description

We've got some, um, classic FORTRAN in-tree that was/is used to generate interpolator taps.

With these changes, that builds on modern platforms.

## Related Issue

Fixes #6521

## Which blocks/areas does this affect?

Effectively, none. (unless you want to be able to reconstruct how the interpolator taps were calculated!)

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Why does someone, who others might consider still has so much of their life ahead of them, know how to pass FORTRAN compiler flags for pre-F77 Fortran? Well, it was a stormy new moon night, and you could faintly hear the faint howling which only your imagination would allow dare to attribute to either a wolf or the storm blowing around a new crack in the roof, when I spotted a dim light flickering at the edge of  the moor, just where my Oracle aarch64 VM was known to rest in many a cold evening. Worriedly, I hastened to pack my FFTwbench and tried to make that run on across the moor and on aarch64 to actually make some sensible benchmarks of how useful that VM would turn out to be for DSP workloads. Alas, a horrible code constitution stopped me from running the FFTwbench…

File: gr-filter/lib/gen_interpolator_taps/generate.sh [hunk 1]
```diff
@@ -6,25 +6,23 @@
 #
 # SPDX-License-Identifier: GPL-3.0-or-later
 #
+set -e
+CC=gcc
+F=gfortran
+FFLAGS=$FFLAGS\ -std=legacy\ -Wall
```
Comment (willcode) [inline gr-filter/lib/gen_interpolator_taps/generate.sh:12]: What are the escaped spaces for?
