### PR TITLE
gr-digital: Fix constellation normalization by average power

### LINKED ISSUE #4892: Constellation power normalization and incorrect soft decision LUT for M-QAM with M > 4
Hello all,

I have a question about the constellation power normalization in [constellation.cc](https://github.com/gnuradio/gnuradio/blob/master/gr-digital/lib/constellation.cc). If using QPSK with power normalization (lines 53-63), the resulting constellation will contain (+-sqrt(2) +-sqrt(2)*j). Doesn't this constellation have an average power of 4?

Secondly, I believe the soft decision LUT generation in this file is incorrect for constellations greater QPSK, because it assumes the constellation is normalized by the max amplitude, and not the average amplitude (line 246), which in the case of QPSK are the same.

### PR DESCRIPTION
**Pull request by dave-pi**
Correct power normalization calculation.
Add a qa test for amplitude and power normalization.

Partially fixes #4892

### CODE REVIEW

**Comment by willcode** [comment]
@dave-pi maint-3.8 has a little different code. Could you see if it's wrong too in a different way?

**Comment by dave-pi** [comment]
> @dave-pi maint-3.8 has a little different code. Could you see if it's wrong too in a different way?
> 
> Looking again ... 3.8 does not have `case POWER_NORMALIZATION` so probably not applicable.

Not applicable. Only change was to replace:
```c
sqrt(c.real() * c.real() + c.imag() * c.imag());
```
with:
```c
std::abs
```

**Comment by dave-pi** [comment]
qa test not right, please do not merge...

**Comment by dave-pi** [comment]
> qa test not right, please do not merge...

Think it's OK now.

**Review by jdemel — APPROVED** [review]
LGTM.
This code is certainly an improvement.

Beyond this PR:
It'd be necessary to clean up some more code in `constellation.cc` in another PR. Maybe this would be a "good first issue" thing. e.g. `summed_mag` is a terrible variable name because it is actively misleading in case of power normalization. `summed_power` would be correct here. Also, it shouldn't be initialized, nor declared, until it is used.

**Comment by dave-pi** [comment]
> LGTM.
> This code is certainly an improvement.
> 
> Beyond this PR:
> It'd be necessary to clean up some more code in `constellation.cc` in another PR. Maybe this would be a "good first issue" thing. e.g. `summed_mag` is a terrible variable name because it is actively misleading in case of power normalization. `summed_power` would be correct here. Also, it shouldn't be initialized, nor declared, until it is used.

Latest commit incorporates these changes.

File: gr-digital/lib/constellation.cc [hunk 1]
```diff
@@ -131,7 +132,7 @@ float constellation::get_distance(unsigned int index, const gr_complex* sample)
 
 unsigned int constellation::get_closest_point(const gr_complex* sample)
 {
-    unsigned int min_index = 0;
+    unsigned int min_index;
     float min_euclid_dist;
     float euclid_dist;
```
Comment (jdemel) [inline gr-digital/lib/constellation.cc:137]: Now that you touched this function, I had a look at it.

https://github.com/gnuradio/gnuradio/blob/7a42de461b4d312fb736abbeeaacd1388a592704/gr-digital/lib/constellation.cc#L133-L149

I suggest to combine declaration and initialization. at least for `min_index` and `min_euclid_dist`. These should be the next 2 lines (L139-140) anyways.

In case of `euclid_dist`, I'm tempted to suggest to move its declaration to line L142. It is more precise to have its declaration there because the variable is only used in the for loop. I doubt this has any negative performance implications.

**Comment by mormj** [comment]
@dave-pi - do you still plan to clean up the `get_closest_point` method?

**Comment by dave-pi** [comment]
> @dave-pi - do you still plan to clean up the `get_closest_point` method?

Sorry thought I had done that already. Yes, will take care of it.

**Comment by dave-pi** [comment]
> > @dave-pi - do you still plan to clean up the `get_closest_point` method?
> 
> Sorry thought I had done that already. Yes, will take care of it.

Done. Did some quick experiments with 3.9 vs master to test functionality.

**Review by mormj — APPROVED** [review]

File: gr-digital/python/digital/qa_constellation.py [hunk 2]
```diff
@@ -177,6 +178,26 @@ def setUp(self):
...
+
+            points = np.array(constel.points())
+            avg_power = np.sum(abs(points)**2) / len(points)
+            self.assertAlmostEqual(avg_power, 1.0, 6)
+            constel = digital.constellation_rect(constel_points, code, rot_sym,
+                                                 side, side, width, width,
+                                                 constellation.AMPLITUDE_NORMALIZATION)
+            points = np.array(constel.points())
+            avg_amp = np.sum(abs(points)) / len(points)
+            self.assertAlmostEqual(avg_amp, 1.0, 6)
```
Comment (mbr0wn) [inline gr-digital/python/digital/qa_constellation.py:199]: I prefer
```suggestion
            self.assertAlmostEqual(avg_amp, 1.0, places=6)
```
...because that method has so many ways of defining "almost". But not a hold-up. This is just my preference.

**Review by mbr0wn — APPROVED** [review]

**Review by mbr0wn — APPROVED** [review]
