### PR TITLE
vocoder: allow input & output rates to differ

### LINKED ISSUE #2932: vocoder: FreeDV modulator outputs incorrect rate for 2400A/2400B modes
There seems to be an issue with the FreeDV modulator when ran with the 2400A/2400B modes.

It works as expected with the `1600` mode:

freedv_works_1600

When switched to the `2400A/2400B` modes, the audio becomes fast as if it is oversampled. 

As a note:
The `2400` modes are designed for VHF operation, with the `2400B` intended to be used with VHF handheld radios/48khz sound cards.

All other modes expect a 8khz input, and will output at 8khz.

The `2400A/2400B` modes will take in 8khz input, output 48khz for the modulator; 48khz input for the demodulator and 8khz audio out. 

audio_fast_8000_input

Example wav output:  [audio_out_2400.zip](https://github.com/gnuradio/gnuradio/files/3899631/audio_out_2400.zip)

I've narrowed it down to the Modulator block's output rate, as a file saved from it and decoded with the `freedv_rx` utility will produce the same audio as the GR (demodulator) block.

modulated_8000

```
./freedv_rx 2400B ~/Desktop/freedv_issue/modulated_8000.raw - | aplay -f S16_LE -r 8000
```

I've also generated the raw modulated bit stream with `freedv_tx` and replayed it in GR, and got an expected result of clear audio.

```
./freedv_tx 2400B ~/sdr/codec2/wav/all.wav - > ~/Desktop/freedv_issue/freedv_txed.raw
```

freedv_2400_raw_input

Original 8khz `all.wav` file for reference: 
[all.zip](https://github.com/gnuradio/gnuradio/files/3899661/all.zip)

### PR DESCRIPTION
**Pull request by argilo**
Fixes #2932.

The input & output rates of the FreeDV modulator aren't necessarily the same. In particular, the 2400A and 2400B modes have an input rate of 8000 sps and an output rate of 48000 sps. To allow for arbitrary input & output rates, I've changed `freedv_tx_ss` from `sync_block` to `block`.

### CODE REVIEW

**Comment by argilo** [comment]
Note: The FreeDV blocks will not be built unless codec2 is available; on Ubuntu it can be installed with `sudo apt install libcodec2-dev`.

To test this change, I used https://github.com/gnuradio/gnuradio/blob/master/gr-vocoder/examples/grfreedv.grc and cycled through all available FreeDV modes.

File: gr-vocoder/lib/freedv_tx_ss_impl.cc [hunk 1]
```diff
@@ -91,17 +92,23 @@ void freedv_tx_ss_impl::set_tx_bpf(bool val)
...
 {
     short* in = (short*)input_items[0];
     short* out = (short*)output_items[0];
     int i;
 
     for (i = 0; i < (noutput_items / d_nom_modem_samples); i++)
-        freedv_tx(
-            d_freedv, &(out[i * d_nom_modem_samples]), &(in[i * d_nom_modem_samples]));
+        freedv_tx(d_freedv, &(out[i * d_nom_modem_samples]), &(in[i * d_speech_samples]));
+    consume(0, i * d_speech_samples);
```
Comment (mormj) [inline gr-vocoder/lib/freedv_tx_ss_impl.cc:111]: It looks like in other general blocks in the codebase with only 1 input, consume_each is always called

Comment (argilo) [reply gr-vocoder/lib/freedv_tx_ss_impl.cc]: Fixed.

**Review by mormj — APPROVED** [review]
LGTM

**Review by willcode — APPROVED** [review]
